"""agents_core.friction_test.report_render — Pure rendering helpers.

render_markdown() and render_json() are pure functions; no IO.
"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .report import FrictionReport


def render_markdown(report: "FrictionReport") -> str:
    lines: list[str] = []

    lines.append(f"# Friction Report - {report.target} ({report.scenario_set}) - {report.started_at}")
    lines.append("")
    lines.append(
        f"**Scenarios:** {report.n_scenarios}    "
        f"**Declared invariants:** {report.n_invariants_declared}    "
        f"**Inferred (provisional):** {report.n_invariants_inferred}"
    )
    lines.append("")

    if report.harness_warnings:
        lines.append("## Harness Warnings")
        lines.append("")
        for w in report.harness_warnings:
            lines.append(f"- {w}")
        lines.append("")

    # Group results
    system_likely = [r for r in report.invariant_results if r.classification == "dissonant_system_likely"]
    model_likely = [r for r in report.invariant_results if r.classification == "dissonant_model_likely"]

    n_total = report.n_dissonances.get("total", 0)
    if n_total == 0:
        lines.append("## Dissonances")
        lines.append("")
        lines.append("None detected in this run.")
        lines.append("")
    else:
        lines.append("## Dissonances")
        lines.append("")
        lines.append(
            "The model said X. Reality said Y. Below are the gaps, "
            "grouped by where the gap most likely lies."
        )
        lines.append("")

        if system_likely:
            lines.append(f"### System-likely dissonance - {len(system_likely)}")
            lines.append("")
            lines.append(
                "These are non-provisional invariants (Erah-ratified or spec-anchored) "
                "that the system failed to satisfy. The model is on stable ground; "
                "the system is the more likely source of the gap."
            )
            lines.append("")
            for r in system_likely:
                sc = _find_scenario_family(report, r.scenario_id)
                lines.append(f"- **{r.invariant_id}** - `{sc}/{r.scenario_id}`")
                lines.append(f"  - dimension: `{r.dimension}`   expected: `{r.expected}`   "
                             f"observed: `{r.observed}`   distance: `{r.distance}`")
                lines.append(f"  - {r.justification}")
                if r.evidence_refs:
                    lines.append(f"  - Evidence: {', '.join(r.evidence_refs)}")
                lines.append("")

        if model_likely:
            lines.append(f"### Model-likely dissonance - {len(model_likely)}")
            lines.append("")
            lines.append(
                "These are provisional invariants - the threshold or expectation was a guess. "
                "Consistent dissonance here may mean the model is wrong, not the system."
            )
            lines.append("")
            # Group by invariant_id
            by_inv: dict[str, list] = {}
            for r in model_likely:
                by_inv.setdefault(r.invariant_id, []).append(r)
            for inv_id, results in by_inv.items():
                lines.append(f"- **{inv_id}** - {len(results)} scenario(s)")
                if results:
                    r0 = results[0]
                    lines.append(f"  - dimension: `{r0.dimension}`   expected: `{r0.expected}`   tolerance: `{r0.tolerance}`")
                    for r in results:
                        lines.append(f"  - observed: `{r.observed}` (`{r.scenario_id}`)")
                    lines.append(f"  - {results[0].justification}")
                lines.append("")

    if report.inferred_invariants:
        lines.append("## Inferred hypotheses (Qwen, all provisional)")
        lines.append("")
        for inv in report.inferred_invariants:
            # Find results for this invariant
            results = [r for r in report.invariant_results if r.invariant_id == inv.invariant_id]
            held_count = sum(1 for r in results if r.status == "held")
            total = len(results)
            lines.append(
                f"- **{inv.invariant_id}** - \"{inv.description}\" - "
                f"held in {held_count}/{total} eligible scenarios. "
                "Candidate for declared promotion if held across the next N runs."
            )
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by friction-tester-v0. Report: `{report.md_path}`*")
    lines.append("")

    return "\n".join(lines)


def render_json(report: "FrictionReport") -> str:
    data = {
        "target": report.target,
        "scenario_set": report.scenario_set,
        "started_at": report.started_at,
        "finished_at": report.finished_at,
        "n_scenarios": report.n_scenarios,
        "n_invariants_declared": report.n_invariants_declared,
        "n_invariants_inferred": report.n_invariants_inferred,
        "n_dissonances": report.n_dissonances,
        "harness_warnings": report.harness_warnings,
        "scenarios": [s.to_dict() for s in report.scenarios],
        "observations": [o.to_dict() for o in report.observations],
        "invariant_results": [r.to_dict() for r in report.invariant_results],
        "inferred_invariants": [
            {
                "id": inv.invariant_id,
                "description": inv.description,
                "dimension": inv.dimension,
                "expected": inv.expected,
                "tolerance": inv.tolerance,
                "proposed_by": inv.proposed_by,
                "provisional": inv.provisional,
            }
            for inv in report.inferred_invariants
        ],
        "md_path": report.md_path,
        "json_path": report.json_path,
    }
    return json.dumps(data, indent=2, default=str)


def _find_scenario_family(report: "FrictionReport", scenario_id: str) -> str:
    for s in report.scenarios:
        if s.scenario_id == scenario_id:
            return s.family_id
    return "unknown"
