"""Typed memory-access seam for /room paths (agents-core stdlib-only submodule).

Unit 0: strict no-op — every resolved path is byte-for-byte identical to today's literal.
"""
from __future__ import annotations

import importlib.resources
import os
import tomllib
from enum import Enum
from pathlib import Path
from typing import Any


class Class(str, Enum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    UNKNOWN = "unknown"


def _load_classmap() -> dict[str, Any]:
    pkg = importlib.resources.files("agents_core.room_paths")
    toml_bytes = (pkg / "_classmap.toml").read_bytes()
    return tomllib.loads(toml_bytes.decode())


_data = _load_classmap()
_KEYS: dict[str, dict] = _data["keys"]
_ROOT_DEFAULT: str = _data.get("root", "/room")


def _get_entry(key: str) -> dict:
    try:
        return _KEYS[key]
    except KeyError:
        raise KeyError(
            f"room_paths: unknown key {key!r}. Use iter_keys() to list valid keys."
        ) from None


def _resolve_base(key: str) -> Path:
    entry = _get_entry(key)
    env_vars: list[str] = entry.get("env_var", [])
    if isinstance(env_vars, str):
        env_vars = [env_vars]
    for var in env_vars:
        val = os.environ.get(var)
        if val:
            return Path(val)
    room_root = os.environ.get("ROOM_ROOT", _ROOT_DEFAULT)
    return Path(room_root) / entry["subpath"]


def room_path(key: str, *parts: str, write: bool = False) -> Path:
    """Return the Path for a /room logical key. write= is a type tag only in Unit 0."""
    base = _resolve_base(key)
    if parts:
        return base.joinpath(*parts)
    return base


def room_str(key: str, *parts: str, write: bool = False) -> str:
    """Return the str for a /room logical key (for recorded/compared-as-str sites)."""
    return str(room_path(key, *parts, write=write))


def path_class(key: str) -> Class:
    """Return the Class enum for a /room logical key."""
    entry = _get_entry(key)
    cls_raw = entry.get("class", "unknown")
    # Handle provisional tags like "C/unknown" or "unknown/B"
    cls_first = cls_raw.split("/")[0].strip()
    try:
        return Class(cls_first)
    except ValueError:
        return Class.UNKNOWN


def access(key: str) -> str:
    """Return the access mode: read|write|both|unknown."""
    entry = _get_entry(key)
    return entry.get("access", "unknown")


def iter_keys() -> list[str]:
    """Return list of all known /room logical keys."""
    return list(_KEYS.keys())


# ---------------------------------------------------------------------------
# Module-level convenience constants — bind at import time (matches today's pattern)
# ---------------------------------------------------------------------------

TARGETS_DIR: Path = room_path("targets")
GPU_QUEUE_DIR: Path = room_path("gpu_queue")
CLAUDE_QUEUE_DIR: Path = room_path("claude_queue")
EXPERTS_ROOT: Path = room_path("experts")
LAPIS_STATE_DIR: Path = room_path("lapis_state")
COUNCIL_DIR: Path = room_path("council")
COUNCIL_LOG_DIR: Path = room_path("council.logs")
AGENT_OBSERVATIONS_DIR: Path = room_path("agent_observations")


# ---------------------------------------------------------------------------
# Shell emitter
# ---------------------------------------------------------------------------

def _emit_sh() -> str:
    lines = [
        "# Generated by: python -m agents_core.room_paths --emit-sh",
        "# DO NOT EDIT — source of truth is agents_core/room_paths/_classmap.toml",
        "",
        f'export ROOM_ROOT="{_ROOT_DEFAULT}"',
        "",
    ]
    for key, entry in _KEYS.items():
        sh_name = "ROOM_" + key.upper().replace(".", "_")
        default_path = Path(_ROOT_DEFAULT) / entry["subpath"]
        lines.append(f'export {sh_name}="{default_path}"')
    lines.append("")
    return "\n".join(lines)


def _emit_rust() -> str:
    lines = [
        "// Generated by: python -m agents_core.room_paths --emit-rust",
        "// DO NOT EDIT — source of truth is agents_core/room_paths/_classmap.toml",
        "",
        f'pub const ROOM_ROOT: &str = "{_ROOT_DEFAULT}";',
        "",
    ]
    for key, entry in _KEYS.items():
        rust_name = "ROOM_" + key.upper().replace(".", "_").replace("-", "_")
        default_path = Path(_ROOT_DEFAULT) / entry["subpath"]
        lines.append(f'pub const {rust_name}: &str = "{default_path}";')
    return "\n".join(lines)
